services:
  scraper:
    ports:
      - "5678:5678"  # Debug port
    volumes:
      - ..:/app  # Mount the entire project for live code updates
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "pipeline.f_runners.scrape_siegessaeule"]
