services:
  orchestrator:
    image: prefecthq/prefect:3-python3.12
    ports:
      - "4200:4200"
    volumes:
      - prefect-data:/root/.prefect
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
      - PREFECT_UI_API_URL=http://127.0.0.1:4200/api
    command: ["prefect", "server", "start"]

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PREFECT_API_URL=http://orchestrator:4200/api
    env_file:
      - ../.env
    depends_on:
      - orchestrator

volumes:
  prefect-data:
