[project]
name = "event-gulper-models"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.38",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
